-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Binary exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object exposing (..)
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Binary
id =
    Object.selectionForField "Int" "id" [] Decode.int


left :
    SelectionSet decodesTo Api.Interface.Expr
    -> SelectionSet decodesTo Api.Object.Binary
left object____ =
    Object.selectionForCompositeField "left" [] object____ Basics.identity


operator :
    SelectionSet decodesTo Api.Object.Token
    -> SelectionSet decodesTo Api.Object.Binary
operator object____ =
    Object.selectionForCompositeField "operator" [] object____ Basics.identity


right :
    SelectionSet decodesTo Api.Interface.Expr
    -> SelectionSet decodesTo Api.Object.Binary
right object____ =
    Object.selectionForCompositeField "right" [] object____ Basics.identity
