-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Block exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Block
id =
    Object.selectionForField "Int" "id" [] Decode.int


statements :
    SelectionSet decodesTo Api.Interface.Stmt
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Block
statements object____ =
    Object.selectionForCompositeField "statements" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)
