-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Interface.Expr exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onAssign : SelectionSet decodesTo Api.Object.Assign
    , onBinary : SelectionSet decodesTo Api.Object.Binary
    , onCall : SelectionSet decodesTo Api.Object.Call
    , onGet : SelectionSet decodesTo Api.Object.Get
    , onGrouping : SelectionSet decodesTo Api.Object.Grouping
    , onLiteral : SelectionSet decodesTo Api.Object.Literal
    , onLogical : SelectionSet decodesTo Api.Object.Logical
    , onSet : SelectionSet decodesTo Api.Object.Set
    , onSuper : SelectionSet decodesTo Api.Object.Super
    , onThis : SelectionSet decodesTo Api.Object.This
    , onUnary : SelectionSet decodesTo Api.Object.Unary
    , onVariable : SelectionSet decodesTo Api.Object.Variable
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Api.Interface.Expr
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "Assign" selections____.onAssign
        , Object.buildFragment "Binary" selections____.onBinary
        , Object.buildFragment "Call" selections____.onCall
        , Object.buildFragment "Get" selections____.onGet
        , Object.buildFragment "Grouping" selections____.onGrouping
        , Object.buildFragment "Literal" selections____.onLiteral
        , Object.buildFragment "Logical" selections____.onLogical
        , Object.buildFragment "Set" selections____.onSet
        , Object.buildFragment "Super" selections____.onSuper
        , Object.buildFragment "This" selections____.onThis
        , Object.buildFragment "Unary" selections____.onUnary
        , Object.buildFragment "Variable" selections____.onVariable
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onAssign = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBinary = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCall = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onGet = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onGrouping = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLiteral = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLogical = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSet = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSuper = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onThis = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnary = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onVariable = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


id : SelectionSet Int Api.Interface.Expr
id =
    Object.selectionForField "Int" "id" [] Decode.int
