-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Assign
    = Assign


type Binary
    = Binary


type Block
    = Block


type Expression
    = Expression


type Grouping
    = Grouping


type Literal
    = Literal


type LiteralBoolean
    = LiteralBoolean


type LiteralFloat
    = LiteralFloat


type LiteralNull
    = LiteralNull


type LiteralString
    = LiteralString


type Print
    = Print


type Token
    = Token


type Unary
    = Unary


type Var
    = Var


type Variable
    = Variable
