-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Assign
    = Assign


type Binary
    = Binary


type Block
    = Block


type Call
    = Call


type Class
    = Class


type Expression
    = Expression


type For
    = For


type Function
    = Function


type Get
    = Get


type Grouping
    = Grouping


type If
    = If


type Literal
    = Literal


type LiteralBoolean
    = LiteralBoolean


type LiteralFloat
    = LiteralFloat


type LiteralNull
    = LiteralNull


type LiteralString
    = LiteralString


type Logical
    = Logical


type Print
    = Print


type Return
    = Return


type Set
    = Set


type Super
    = Super


type This
    = This


type Token
    = Token


type Unary
    = Unary


type Var
    = Var


type Variable
    = Variable


type While
    = While
